### ISSUE TITLE
代码高亮无效

### ISSUE THREAD

**Issue by wekerSnail** [Halyul/hexo-theme-mdui#96]
主题配置
```
# Post
post:
  entry_excerpt: 80
  random_pics: 44
  qr_code: false
  prism:
    theme: coy
    line_number: true
  license:
    name: 'CC BY-NC-SA 4.0'
    link:  'https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh'
  word_count: false
  read_time: false
```
*hexo s --debug 不保存，console也不报错，就是页面代码无高亮，也没有行数显示，hexo主配置已关闭默认的高亮配置*
